/* ==========================================================================
   Строки сайта, которых нет в словаре мобильного приложения.
   Формат: ключ: [русский, o‘zbekcha, English]. Словарь приложения (I18N)
   проверяется первым — эти строки его не перекрывают, а дополняют.
   ========================================================================== */
"use strict";

const STR = {
  age_adult:["от 12 лет","12 yoshdan","12+ years"],
  age_child:["2–11 лет","2–11 yosh","2–11 years"],
  age_child_tour:["2–11 лет, своё место","2–11 yosh, alohida o‘rin","2–11 years, own seat"],
  age_infant:["до 2 лет, без места","2 yoshgacha, o‘rindiqsiz","under 2, on lap"],
  aircraft_class:["Класс самолёта","Samolyot sinfi","Aircraft class"],
  airlines:["Авиакомпании","Aviakompaniyalar","Airlines"],
  all:["Все","Barchasi","All"],
  all_services:["Услуги","Xizmatlar","Services"],
  all_services_sub:["Одна касса для всего путешествия: оплата, документы и поддержка — в одном месте","Butun sayohat uchun bitta kassa: to‘lov, hujjatlar va yordam — bir joyda","One checkout for the whole trip: payment, documents and support in one place"],
  am_beach:["Свой пляж","O‘z plyaji","Private beach"],
  am_golf:["Гольф","Golf","Golf"],
  am_kids:["Детский клуб","Bolalar klubi","Kids club"],
  am_pool:["Бассейн","Basseyn","Pool"],
  am_spa:["СПА","SPA","Spa"],
  am_wifi:["Wi‑Fi","Wi‑Fi","Wi‑Fi"],
  any_price:["Любая цена","Istalgan narx","Any price"],
  back:["Назад","Orqaga","Back"],
  back_results:["К результатам","Natijalarga qaytish","Back to results"],
  beach_first:["Первая линия","Birinchi qator","Beachfront"],
  beach_m:["{m} м до пляжа","Plyajgacha {m} m","{m} m to the beach"],
  beach_none:["Городской отель","Shahar mehmonxonasi","City hotel"],
  board:["Питание","Ovqatlanish","Meals"],
  board_AI:["всё включено","hammasi kiritilgan","all inclusive"],
  board_BB:["завтраки","nonushta","breakfast"],
  board_HB:["завтрак и ужин","nonushta va kechki ovqat","half board"],
  board_RO:["без питания","ovqatsiz","room only"],
  board_UAI:["ультра всё включено","ultra hammasi kiritilgan","ultra all inclusive"],
  book:["Забронировать","Bron qilish","Book"],
  book_tour:["Оформить тур","Turni rasmiylashtirish","Book this tour"],
  change_number:["Изменить номер","Raqamni o‘zgartirish","Change number"],
  change_out:["Изменить рейс туда","Borish reysini o‘zgartirish","Change outbound flight"],
  checkin:["Заезд","Kirish","Check-in"],
  checkin_from:["с 14:00","14:00 dan","from 14:00"],
  checkout:["Выезд","Chiqish","Check-out"],
  checkout_title:["Оформление","Rasmiylashtirish","Checkout"],
  checkout_until:["до 12:00","12:00 gacha","until 12:00"],
  children_free:["до 12 лет — бесплатно","12 yoshgacha — bepul","under 12 stay free"],
  choose_room:["Выбрать номер","Xonani tanlash","Choose a room"],
  city:["Город","Shahar","City"],
  clear_filters:["Сбросить фильтры","Filtrlarni tozalash","Clear filters"],
  cls_auto:["Подобрать по числу пассажиров","Yo‘lovchilar soniga qarab tanlash","Match to passenger count"],
  confirming_body:["Оплата получена. Оператор подтверждает борт и экипаж — ваучер появится здесь.","To‘lov qabul qilindi. Operator samolyot va ekipajni tasdiqlamoqda — vaucher shu yerda paydo bo‘ladi.","Payment received. The operator is confirming the aircraft and crew — the voucher will appear here."],
  confirming_title:["Подтверждаем борт","Samolyotni tasdiqlayapmiz","Confirming the aircraft"],
  contact_details:["Контакты","Aloqa","Contact details"],
  cur_uzs:["сум","so‘m","UZS"],
  customer:["Заказчик","Buyurtmachi","Customer"],
  date:["Дата","Sana","Date"],
  dates:["Даты","Sanalar","Dates"],
  demo_banner:["Демонстрация на тестовых данных","Test ma’lumotlaridagi namoyish","Demo on test data"],
  demo_footer:["Демонстрация на тестовых данных: деньги не списываются, названия отелей вымышлены, цены условные.","Test ma’lumotlaridagi namoyish: pul yechilmaydi, mehmonxona nomlari o‘ylab topilgan, narxlar shartli.","Demo on test data: no money is charged, hotel names are fictional, prices are indicative."],
  dep_time:["Время вылета","Uchish vaqti","Departure time"],
  details:["Подробнее","Batafsil","Details"],
  distance:["Расстояние","Masofa","Distance"],
  doc_FLIGHT:["Электронный билет","Elektron chipta","E-ticket"],
  doc_HELI:["Ваучер на вертолёт","Vertolyot vaucheri","Helicopter voucher"],
  doc_HOTEL:["Ваучер на отель","Mehmonxona vaucheri","Hotel voucher"],
  doc_JET:["Ваучер на частный рейс","Xususiy reys vaucheri","Private flight voucher"],
  doc_TOUR:["Туристический ваучер","Turistik vaucher","Tour voucher"],
  doc_sent:["Документы отправлены на {to} и сохранены в разделе «Мои заказы»","Hujjatlar {to} ga yuborildi va «Buyurtmalarim» bo‘limida saqlandi","Documents sent to {to} and saved in My orders"],
  email_opt:["Email — необязательно","Email — ixtiyoriy","Email — optional"],
  err_checkout:["Дата выезда должна быть позже заезда","Chiqish sanasi kirishdan keyin bo‘lishi kerak","Check-out must be after check-in"],
  err_code:["Введите четыре цифры","To‘rtta raqam kiriting","Enter four digits"],
  err_contact:["Укажите телефон в формате +998 XX XXX XX XX","Telefonni +998 XX XXX XX XX formatida kiriting","Enter a phone as +998 XX XXX XX XX"],
  err_date_past:["Эта дата уже прошла","Bu sana o‘tib ketgan","This date has passed"],
  err_dob:["Укажите дату рождения","Tug‘ilgan sanani kiriting","Enter the date of birth"],
  err_email:["Проверьте адрес почты","Email manzilini tekshiring","Check the email address"],
  err_expiry:["Паспорт истекает раньше, чем закончится поездка","Pasport muddati safar tugashidan oldin tugaydi","The passport expires before the trip ends"],
  err_gender:["Укажите пол","Jinsini tanlang","Select gender"],
  err_generic:["Не удалось открыть страницу. Вернитесь на главную.","Sahifani ochib bo‘lmadi. Bosh sahifaga qayting.","This page could not be opened. Go back to the home page."],
  err_name:["Имя и фамилия — латиницей, как в паспорте","Ism va familiya — pasportdagidek lotin harflarida","Name in Latin letters, exactly as in the passport"],
  err_nights_max:["Не больше 30 ночей в одном бронировании","Bitta bronda 30 kechadan ortiq emas","Up to 30 nights per booking"],
  err_passport:["Номер паспорта — от 5 до 9 латинских букв и цифр","Pasport raqami — 5 dan 9 gacha lotin harf va raqam","Passport number: 5 to 9 Latin letters and digits"],
  err_phone:["Введите номер в формате +998 XX XXX XX XX","Raqamni +998 XX XXX XX XX formatida kiriting","Enter a number as +998 XX XXX XX XX"],
  err_return:["Обратный рейс раньше вылета","Qaytish sanasi uchishdan oldin","Return is before departure"],
  err_rooms:["Не больше трёх взрослых в номере — добавьте номер","Bir xonada uchtadan ortiq katta bo‘lmaydi — xona qo‘shing","Up to three adults per room — add a room"],
  err_same_city:["Город вылета и прилёта совпадают","Uchish va qo‘nish shaharlari bir xil","Departure and arrival are the same"],
  err_your_name:["Укажите имя","Ismingizni kiriting","Enter your name"],
  est_line:["≈ {h} в пути, {m}","≈ {h} yo‘lda, {m}","≈ {h} in the air, {m}"],
  estimate:["Предварительная стоимость","Taxminiy narx","Estimated price"],
  estimate_note:["Точную цену менеджер пришлёт после проверки борта и слотов в аэропортах. Оплата — только после вашего подтверждения.","Aniq narxni menejer samolyot va aeroport slotlarini tekshirgach yuboradi. To‘lov — faqat sizning tasdig‘ingizdan keyin.","A manager sends the exact price after checking the aircraft and airport slots. You pay only after you confirm."],
  fare_note:["Цена перепроверяется у перевозчика перед оплатой","Narx to‘lovdan oldin aviakompaniyada qayta tekshiriladi","The fare is rechecked with the airline before payment"],
  filters:["Фильтры","Filtrlar","Filters"],
  find_hotels:["Найти отели","Mehmonxona topish","Find hotels"],
  find_tours:["Найти туры","Tur topish","Find tours"],
  flight_rt:["Перелёт туда и обратно","Borish-qaytish parvozi","Return flight"],
  flight_time:["Время в пути","Parvoz vaqti","Flight time"],
  for_nights:["за {n}","{n} uchun","for {n}"],
  found_hotels:["Найдено отелей: {n}","Topilgan mehmonxonalar: {n}","{n} hotels found"],
  found_n:["Найдено рейсов: {n}","Topilgan reyslar: {n}","{n} flights found"],
  found_tours:["Найдено туров: {n}","Topilgan turlar: {n}","{n} tours found"],
  gender_f:["Женский","Ayol","Female"],
  gender_m:["Мужской","Erkak","Male"],
  grp_international:["Международные","Xalqaro","International"],
  grp_uzbekistan:["Узбекистан","O‘zbekiston","Uzbekistan"],
  guest_details:["Данные гостя","Mehmon ma’lumotlari","Guest details"],
  guest_note:["Заказы сохраняются в этом браузере","Buyurtmalar shu brauzerda saqlanadi","Orders are kept in this browser"],
  guests:["Гости","Mehmonlar","Guests"],
  heli_base:["Ташкент, вертолётная площадка","Toshkent, vertolyot maydonchasi","Tashkent heliport"],
  heli_calc:["Рассчитать полёт","Parvozni hisoblash","Price this flight"],
  heli_max:["до 18 на Ми‑8","Mi‑8 da 18 tagacha","up to 18 on a Mi‑8"],
  heli_note_ph:["Например: пикник на Чарваке, обратно в 18:00","Masalan: Chorvoqda piknik, 18:00 da qaytish","For example: a picnic at Charvak, back at 18:00"],
  heli_rt:["Туда и обратно","Borish va qaytish","Return trip"],
  heli_sub:["Горы, озёра и Самарканд — без дороги и пробок. Посадка на подготовленных площадках.","Tog‘lar, ko‘llar va Samarqand — yo‘lsiz va tirbandliksiz. Tayyorlangan maydonchalarga qo‘nish.","Mountains, lakes and Samarkand without the road or traffic. Landing on prepared pads."],
  heli_title:["Вертолёт","Vertolyot","Helicopter"],
  heli_tour_note:["Обзорный полёт длится 30 минут, взлёт и посадка — в Ташкенте","Sayr parvozi 30 daqiqa davom etadi, uchish va qo‘nish — Toshkentda","The sightseeing flight lasts 30 minutes, taking off and landing in Tashkent"],
  heli_type:["Вертолёт","Vertolyot","Helicopter"],
  hero_eyebrow:["Charteri · авиабилеты, туры, отели и частные рейсы","Charteri · aviachiptalar, turlar, mehmonxonalar va xususiy reyslar","Charteri · flights, tours, hotels and private charters"],
  hero_flights:["Куда летим?","Qayerga uchamiz?","Where are we flying?"],
  hero_flights_sub:["Чартерные и регулярные рейсы из Узбекистана. Цена перепроверяется перед оплатой.","O‘zbekistondan charter va muntazam reyslar. Narx to‘lovdan oldin qayta tekshiriladi.","Charter and scheduled flights from Uzbekistan. The fare is rechecked before you pay."],
  hero_heli:["Вертолёт — в горы за полчаса","Vertolyotda — tog‘larga yarim soatda","By helicopter — the mountains in half an hour"],
  hero_heli_sub:["Чимган, Амирсой, Чарвак, Заамин, Самарканд или обзорный полёт над Ташкентом.","Chimyon, Amirsoy, Chorvoq, Zomin, Samarqand yoki Toshkent ustidan sayr parvozi.","Chimgan, Amirsoy, Charvak, Zaamin, Samarkand — or a sightseeing flight over Tashkent."],
  hero_hotels:["Отели на курортах","Kurortlardagi mehmonxonalar","Resort hotels"],
  hero_hotels_sub:["Анталия, Дубай, Стамбул, Шарм-эль-Шейх, Нячанг и Пхукет. Дети до 12 лет — бесплатно.","Antaliya, Dubay, Istanbul, Sharm ash-Shayx, Nyachang va Phuket. 12 yoshgacha bolalar — bepul.","Antalya, Dubai, Istanbul, Sharm El Sheikh, Nha Trang and Phuket. Children under 12 stay free."],
  hero_jet:["Частный самолёт — по вашему расписанию","Xususiy samolyot — sizning jadvalingiz bo‘yicha","A private jet on your schedule"],
  hero_jet_sub:["Из любого аэропорта Узбекистана. Оценка стоимости сразу, точная цена — от менеджера.","O‘zbekistonning istalgan aeroportidan. Narx darhol baholanadi, aniq narxni menejer beradi.","From any airport in Uzbekistan. An estimate right away, the exact price from a manager."],
  hero_tours:["Тур на море: перелёт, отель и трансфер","Dengizga tur: parvoz, mehmonxona va transfer","Beach holidays: flight, hotel and transfer"],
  hero_tours_sub:["Пакетом на 7% дешевле, чем покупать всё отдельно. Страховка включена.","Paket holida alohida sotib olishdan 7% arzon. Sug‘urta kiritilgan.","7% cheaper as a package than bought separately. Insurance included."],
  history:["История заказа","Buyurtma tarixi","Order history"],
  home:["На главную","Bosh sahifa","Home"],
  hotel:["Отель","Mehmonxona","Hotel"],
  hotel_note:["Цена за весь срок проживания, налоги включены. Бесплатная отмена — до 7 дней до заезда.","Butun yashash muddati uchun narx, soliqlar kiritilgan. Bepul bekor qilish — kirishdan 7 kun oldingacha.","Price for the whole stay, taxes included. Free cancellation up to 7 days before check-in."],
  hour:["час","soat","hour"],
  how_1:["Выберите","Tanlang","Choose"],
  how_1_d:["Рейс, тур, отель или борт — цены из тех же систем, с которыми работают агентства.","Reys, tur, mehmonxona yoki samolyot — narxlar agentliklar ishlaydigan tizimlardan.","A flight, tour, hotel or aircraft — prices from the same systems agencies use."],
  how_2:["Оплатите","To‘lang","Pay"],
  how_2_d:["Payme, Click, Uzum, Uzcard, Humo или Visa и Mastercard. Цена проверяется перед списанием.","Payme, Click, Uzum, Uzcard, Humo yoki Visa va Mastercard. Narx yechishdan oldin tekshiriladi.","Payme, Click, Uzum, Uzcard, Humo, or Visa and Mastercard. The price is checked before you’re charged."],
  how_3:["Летите","Uching","Fly"],
  how_3_d:["Билет или ваучер с QR-кодом — в «Моих заказах» и на телефоне, открывается без интернета.","QR-kodli chipta yoki vaucher — «Buyurtmalarim»da va telefonda, internetsiz ochiladi.","A ticket or voucher with a QR code in My orders and on your phone, opens offline."],
  how_title:["Как это работает","Bu qanday ishlaydi","How it works"],
  incl_flight:["Перелёт","Parvoz","Flight"],
  incl_flight_full:["Перелёт туда и обратно, багаж 20 кг","Borish-qaytish parvozi, 20 kg yuk","Return flight with 20 kg baggage"],
  incl_hotel_full:["Отель, {n}, питание: {b}","Mehmonxona, {n}, ovqatlanish: {b}","Hotel, {n}, meals: {b}"],
  incl_insurance:["Страховка","Sug‘urta","Insurance"],
  incl_insurance_full:["Медицинская страховка на весь срок","Butun muddatga tibbiy sug‘urta","Medical insurance for the whole trip"],
  incl_transfer:["Трансфер","Transfer","Transfer"],
  incl_transfer_full:["Трансфер аэропорт — отель — аэропорт","Aeroport — mehmonxona — aeroport transferi","Airport — hotel — airport transfer"],
  included:["включено","kiritilgan","included"],
  infant_fare:["Младенец, 10% тарифа","Chaqaloq, tarifning 10%","Infant, 10% of fare"],
  insurance:["Страховка","Sug‘urta","Insurance"],
  insurance_basic:["Медицинская, базовая","Tibbiy, asosiy","Medical, basic"],
  jet_calc:["Рассчитать и оформить","Hisoblash va rasmiylashtirish","Get an estimate"],
  jet_heavy:["Тяжёлый","Og‘ir","Heavy jet"],
  jet_light:["Лёгкий","Yengil","Light jet"],
  jet_max:["до 14 пассажиров","14 yo‘lovchigacha","up to 14 passengers"],
  jet_mid:["Средний","O‘rta","Midsize jet"],
  jet_note_ph:["Например: кейтеринг, перевозка собаки, встреча у трапа","Masalan: ovqat, itni olib ketish, trap oldida kutib olish","For example: catering, travelling with a dog, meet at the aircraft"],
  jet_sub:["Выберите маршрут и класс самолёта — оценка стоимости появится сразу.","Yo‘nalish va samolyot sinfini tanlang — narx bahosi darhol chiqadi.","Choose the route and aircraft class — the estimate appears right away."],
  jet_supermid:["Супер-средний","Super o‘rta","Super-midsize jet"],
  jet_title:["Частный самолёт","Xususiy samolyot","Private jet"],
  kg:["кг","kg","kg"],
  km:["км","km","km"],
  lead_guest:["Основной гость","Asosiy mehmon","Lead guest"],
  mgr_body:["Заявка принята. Менеджер проверяет борт и слоты в аэропортах и пришлёт точную цену — обычно за 15 минут.","So‘rov qabul qilindi. Menejer samolyot va aeroport slotlarini tekshirib, aniq narxni yuboradi — odatda 15 daqiqada.","Request received. A manager is checking the aircraft and airport slots and will send the exact price, usually within 15 minutes."],
  mgr_title:["Менеджер готовит предложение","Menejer taklif tayyorlamoqda","A manager is preparing your quote"],
  min:["мин","daq","min"],
  mod_flights:["Авиабилеты","Aviachiptalar","Flights"],
  mod_heli:["Вертолёты","Vertolyotlar","Helicopters"],
  mod_hotels:["Отели","Mehmonxonalar","Hotels"],
  mod_jet:["Частные самолёты","Xususiy samolyotlar","Private jets"],
  mod_tours:["Туры","Turlar","Tours"],
  my_orders:["Мои заказы","Buyurtmalarim","My orders"],
  nights:["Ночей","Kechalar","Nights"],
  no_aircraft:["Для такого числа пассажиров нет подходящего борта — уменьшите число или выберите другой класс","Bunday yo‘lovchilar soni uchun mos samolyot yo‘q — sonni kamaytiring yoki boshqa sinfni tanlang","No aircraft fits this many passengers — reduce the number or choose another class"],
  order_missing:["Заказ не найден","Buyurtma topilmadi","Order not found"],
  orders_count:["Заказов: {n}","Buyurtmalar: {n}","Orders: {n}"],
  orders_empty:["Заказов пока нет","Hozircha buyurtmalar yo‘q","No orders yet"],
  orders_empty_d:["Билеты, ваучеры и заявки появятся здесь","Chiptalar, vaucherlar va so‘rovlar shu yerda paydo bo‘ladi","Tickets, vouchers and requests will appear here"],
  orders_sub:["Билеты, ваучеры и заявки на частные рейсы","Chiptalar, vaucherlar va xususiy reyslarga so‘rovlar","Tickets, vouchers and private flight requests"],
  package_discount:["Пакетная скидка 7%","Paket chegirmasi 7%","Package discount 7%"],
  pax_adult:["Взрослый","Katta","Adult"],
  pax_child:["Ребёнок","Bola","Child"],
  pax_infant:["Младенец","Chaqaloq","Infant"],
  payment:["Оплата","To‘lov","Payment"],
  per_night:["{p} за ночь","kechasiga {p}","{p} per night"],
  per_person:["за человека","bir kishi uchun","per person"],
  phone_label:["Номер телефона","Telefon raqami","Phone number"],
  popular_dest:["Популярные направления","Ommabop yo‘nalishlar","Popular destinations"],
  popular_dest_sub:["Цены на вылет из Ташкента через две недели","Ikki haftadan keyin Toshkentdan uchish narxlari","Prices for departures from Tashkent in two weeks"],
  price_calendar:["Цены по датам","Sanalar bo‘yicha narxlar","Prices by date"],
  price_night:["Цена за ночь","Kechalik narx","Price per night"],
  price_ready:["Цена готова","Narx tayyor","Your quote is ready"],
  price_ready_d:["Менеджер подтвердил борт и стоимость. Оплатите, чтобы закрепить рейс.","Menejer samolyot va narxni tasdiqladi. Reysni band qilish uchun to‘lang.","The manager confirmed the aircraft and price. Pay to secure the flight."],
  reset_confirm:["Вернуть демонстрацию к исходным данным?","Namoyish boshlang‘ich holatga qaytarilsinmi?","Reset the demo to its starting data?"],
  reset_demo:["Сбросить демо","Demoni qayta boshlash","Reset demo"],
  room:["Номер","Xona","Room"],
  room_deluxe:["Делюкс","Deluks","Deluxe"],
  room_deluxe_d:["вид на море или город","dengiz yoki shahar manzarasi","sea or city view"],
  room_family:["Семейный","Oilaviy","Family room"],
  room_family_d:["две комнаты, до 4 гостей","ikki xona, 4 mehmongacha","two rooms, up to 4 guests"],
  room_standard:["Стандарт","Standart","Standard"],
  room_standard_d:["двуспальная кровать или две раздельные","ikki kishilik yoki ikkita alohida karavot","double or twin beds"],
  room_suite:["Люкс","Lyuks","Suite"],
  room_suite_d:["гостиная и спальня, лучший вид","mehmonxona va yotoqxona, eng yaxshi manzara","living room and bedroom, best view"],
  rooms:["Номера","Xonalar","Rooms"],
  rooms_title:["Номера","Xonalar","Rooms"],
  route:["Маршрут","Yo‘nalish","Route"],
  route_when:["Маршрут и время","Yo‘nalish va vaqt","Route and time"],
  save_vs:["Выгоднее на {s}","{s} tejaysiz","Save {s}"],
  seats_left:["Осталось мест: {n}","Qolgan o‘rinlar: {n}","{n} seats left"],
  send_request:["Отправить заявку","So‘rov yuborish","Send request"],
  settings:["Настройки","Sozlamalar","Settings"],
  sign_in:["Войти","Kirish","Sign in"],
  signed_in:["Вы вошли","Siz kirdingiz","Signed in"],
  signed_out:["Вы вышли","Siz chiqdingiz","Signed out"],
  sort_rating:["По рейтингу","Reyting bo‘yicha","Top rated"],
  sort_stars:["По звёздам","Yulduzlar bo‘yicha","By stars"],
  sqm:["м²","m²","m²"],
  st_CANCELLED:["Отменён","Bekor qilindi","Cancelled"],
  st_COMPLETED:["Выполнен","Bajarildi","Completed"],
  st_CONFIRMED:["Подтверждён","Tasdiqlandi","Confirmed"],
  st_NEW:["Заявка принята","So‘rov qabul qilindi","Request received"],
  st_PAID:["Оплачен","To‘landi","Paid"],
  st_PENDING:["Ждёт оплаты","To‘lov kutilmoqda","Awaiting payment"],
  st_REFUNDED:["Возврат","Qaytarildi","Refunded"],
  stars_label:["Звёзды","Yulduzlar","Stars"],
  svc_flights:["Регулярные и чартерные рейсы, календарь цен, электронный билет с QR","Muntazam va charter reyslar, narxlar taqvimi, QR-kodli elektron chipta","Scheduled and charter flights, a price calendar, e-ticket with QR"],
  svc_heli:["Горы и озёра Ташкентской области, Самарканд, обзорные полёты","Toshkent viloyati tog‘lari va ko‘llari, Samarqand, sayr parvozlari","Mountains and lakes near Tashkent, Samarkand, sightseeing flights"],
  svc_hotels:["Курортные и городские отели, фильтр по звёздам и питанию","Kurort va shahar mehmonxonalari, yulduz va ovqat bo‘yicha filtr","Resort and city hotels, filter by stars and meals"],
  svc_jet:["Бизнес-джеты от лёгких до тяжёлых, оценка стоимости сразу","Yengildan og‘irgacha biznes-jetlar, narx darhol baholanadi","Business jets from light to heavy, instant estimate"],
  svc_tours:["Перелёт, отель и трансфер одним заказом, дешевле на 7%","Parvoz, mehmonxona va transfer bitta buyurtmada, 7% arzonroq","Flight, hotel and transfer in one booking, 7% cheaper"],
  swap:["Поменять местами","Almashtirish","Swap"],
  t_day:["День","Kunduzi","Afternoon"],
  t_evening:["Вечер","Kechqurun","Evening"],
  t_morning:["Утро","Ertalab","Morning"],
  t_night:["Ночь","Tunda","Night"],
  theme_system:["Авто","Avto","Auto"],
  time:["Время","Vaqt","Time"],
  to_checkout:["Перейти к оформлению","Rasmiylashtirishga o‘tish","Continue to checkout"],
  toast_confirmed:["Борт по заказу {no} подтверждён","{no} buyurtma bo‘yicha samolyot tasdiqlandi","Aircraft confirmed for {no}"],
  toast_priced:["Менеджер прислал цену по заявке {no}","Menejer {no} so‘rov bo‘yicha narx yubordi","The manager sent a price for {no}"],
  tour_flights:["Рейсы тура","Tur reyslari","Tour flights"],
  tour_includes:["Что входит в тур","Turga nimalar kiradi","What’s included"],
  tour_pp:["{p} за человека","bir kishi uchun {p}","{p} per person"],
  tour_price:["Стоимость тура","Tur narxi","Tour price"],
  tour_to:["Направление:","Yo‘nalish:","Destination:"],
  tourists:["Туристы","Turistlar","Travellers"],
  transfer:["Трансфер","Transfer","Transfer"],
  transfer_group:["Групповой, аэропорт — отель — аэропорт","Guruhli, aeroport — mehmonxona — aeroport","Shared, airport — hotel — airport"],
  trip_kind:["Тип рейса","Reys turi","Trip type"],
  trust_1:["Цена проверяется перед оплатой","Narx to‘lovdan oldin tekshiriladi","The price is checked before you pay"],
  trust_1_d:["Если поставщик изменил цену, вы увидите старую и новую сумму и решите сами","Agar ta’minotchi narxni o‘zgartirsa, eski va yangi summani ko‘rib, o‘zingiz qaror qilasiz","If the supplier changes the price, you see the old and new amounts and decide"],
  trust_2:["Три языка","Uch til","Three languages"],
  trust_2_d:["Сайт, документы и поддержка — на узбекском, русском и английском","Sayt, hujjatlar va yordam — o‘zbek, rus va ingliz tillarida","Site, documents and support in Uzbek, Russian and English"],
  trust_3:["Документ без интернета","Internetsiz hujjat","Documents work offline"],
  trust_3_d:["Билет и ваучер с QR-кодом открываются в аэропорту даже без роуминга","QR-kodli chipta va vaucher aeroportda rouminsiz ham ochiladi","Tickets and vouchers with QR codes open at the airport even without roaming"],
  type_FLIGHT:["Авиабилеты","Aviachiptalar","Flights"],
  type_HELI:["Вертолёты","Vertolyotlar","Helicopters"],
  type_HOTEL:["Отели","Mehmonxonalar","Hotels"],
  type_JET:["Самолёты","Samolyotlar","Jets"],
  type_TOUR:["Туры","Turlar","Tours"],
  up_to_seats:["до {n} мест","{n} o‘ringacha","up to {n} seats"],
  via:["через {c}","{c} orqali","via {c}"],
  view_voucher:["Открыть ваучер","Vaucherni ochish","Open voucher"],
  we_accept:["Принимаем к оплате","To‘lovga qabul qilamiz","We accept"],
  where_to:["Куда","Qayerga","Destination"],
  wishes:["Пожелания","Istaklar","Special requests"],
  your_fare:["Ваш тариф","Sizning tarifingiz","Your fare"],
  your_name:["Ваше имя","Ismingiz","Your name"]
};

/* Склонения. Русский: [1, 2–4, 5+]; английский: [1, много]; узбекский не склоняет. */
const PL = {
  adult:   { ru:["взрослый","взрослых","взрослых"], uz:["katta"],     en:["adult","adults"] },
  child:   { ru:["ребёнок","ребёнка","детей"],       uz:["bola"],      en:["child","children"] },
  guest:   { ru:["гость","гостя","гостей"],          uz:["mehmon"],    en:["guest","guests"] },
  night:   { ru:["ночь","ночи","ночей"],             uz:["kecha"],     en:["night","nights"] },
  pax:     { ru:["пассажир","пассажира","пассажиров"], uz:["yo‘lovchi"], en:["passenger","passengers"] },
  room:    { ru:["номер","номера","номеров"],        uz:["xona"],      en:["room","rooms"] },
  tourist: { ru:["турист","туриста","туристов"],     uz:["turist"],    en:["traveller","travellers"] }
};

/* Поправки к словарю приложения. boarding: uz «Qo‘nish» значит «приземление» —
   русское «Посадка» двусмысленно, и перевод взял не то значение. На талоне это
   время посадки в самолёт, поэтому «Bortga chiqish». В приложении — отдельная задача. */
const I18N_FIX = { boarding: { uz: "Bortga chiqish" } };
for (const [k, v] of Object.entries(I18N_FIX)) Object.assign(I18N[k], v);
